"""
Geração de relatório PDF (bilíngue: arquivos separados PT/EN), com
metadados, histórico de operações e gráficos de histograma antes/depois.

Usa matplotlib para gerar os gráficos como imagens, e reportlab para
montar o documento PDF.
"""
from __future__ import annotations

import io
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

import numpy as np
import matplotlib
matplotlib.use("Agg")  # backend não-interativo, seguro para gerar imagens em memória
import matplotlib.pyplot as plt

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage, PageBreak,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


@dataclass
class ReportData:
    """Dados necessários para montar o relatório, já extraídos do app."""
    image_name: str
    image_path: str
    width: int
    height: int
    band_count: int
    dtype: str
    crs: Optional[str]
    nodata: Optional[float]
    driver: Optional[str]
    compression: Optional[str]
    operations: list[str]  # labels das operações aplicadas, em ordem
    histogram_original: Optional[np.ndarray] = None  # shape (bands, H, W) reduzido (preview)
    histogram_corrected: Optional[np.ndarray] = None
    band_composition: tuple[int, int, int] = (1, 1, 1)


_TEXT = {
    "pt": {
        "title": "Relatório de Processamento — GeoEqualize",
        "generated_at": "Gerado em",
        "section_metadata": "1. Metadados da Imagem",
        "field_name": "Nome do arquivo",
        "field_path": "Caminho",
        "field_dimensions": "Dimensões (px)",
        "field_bands": "Número de bandas",
        "field_dtype": "Tipo de dado",
        "field_crs": "CRS",
        "field_nodata": "NoData",
        "field_driver": "Driver",
        "field_compression": "Compressão",
        "field_composition": "Composição RGB exibida",
        "section_operations": "2. Operações Aplicadas",
        "no_operations": "Nenhuma operação foi aplicada a esta imagem.",
        "section_histogram": "3. Histograma — Antes e Depois",
        "histogram_caption": "Comparação da distribuição de valores de pixel antes e depois das correções.",
        "footer": "Relatório gerado automaticamente pelo GeoEqualize.",
    },
    "en": {
        "title": "Processing Report — GeoEqualize",
        "generated_at": "Generated on",
        "section_metadata": "1. Image Metadata",
        "field_name": "File name",
        "field_path": "Path",
        "field_dimensions": "Dimensions (px)",
        "field_bands": "Number of bands",
        "field_dtype": "Data type",
        "field_crs": "CRS",
        "field_nodata": "NoData",
        "field_driver": "Driver",
        "field_compression": "Compression",
        "field_composition": "Displayed RGB composition",
        "section_operations": "2. Applied Operations",
        "no_operations": "No operations were applied to this image.",
        "section_histogram": "3. Histogram — Before and After",
        "histogram_caption": "Comparison of pixel value distribution before and after corrections.",
        "footer": "Report automatically generated by GeoEqualize.",
    },
}


def _render_histogram_figure(
    original: Optional[np.ndarray],
    corrected: Optional[np.ndarray],
    lang: str,
) -> Optional[bytes]:
    """Renderiza um gráfico comparativo de histograma como PNG em memória."""
    if original is None:
        return None

    labels = {
        "pt": {"before": "Antes", "after": "Depois", "value": "Valor do pixel", "count": "Contagem"},
        "en": {"before": "Before", "after": "After", "value": "Pixel value", "count": "Count"},
    }[lang]

    fig, ax = plt.subplots(figsize=(6.2, 3.4), dpi=150)

    band_colors = ["#d62728", "#2ca02c", "#1f77b4"]
    bands = min(original.shape[0], 3) if original.shape[0] >= 3 else 1

    for i in range(bands):
        flat = original[i].astype(np.float64).ravel()
        flat = flat[np.isfinite(flat)]
        if flat.size:
            ax.hist(flat, bins=64, alpha=0.35, color=band_colors[i % 3],
                     label=f"{labels['before']} B{i+1}", histtype="stepfilled")

        if corrected is not None:
            flat_c = corrected[i].astype(np.float64).ravel()
            flat_c = flat_c[np.isfinite(flat_c)]
            if flat_c.size:
                ax.hist(flat_c, bins=64, alpha=0.7, color=band_colors[i % 3],
                         label=f"{labels['after']} B{i+1}", histtype="step", linewidth=1.6)

    ax.set_xlabel(labels["value"])
    ax.set_ylabel(labels["count"])
    ax.legend(fontsize=7, loc="upper right")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    fig.tight_layout()

    buffer = io.BytesIO()
    fig.savefig(buffer, format="png")
    plt.close(fig)
    buffer.seek(0)
    return buffer.read()


def generate_pdf_report(data: ReportData, output_path: Path, lang: str = "pt") -> None:
    """Gera um relatório PDF no idioma especificado ('pt' ou 'en')."""
    if lang not in _TEXT:
        raise ValueError(f"Idioma não suportado: {lang}")
    texts = _TEXT[lang]

    output_path.parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        str(output_path), pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm, topMargin=2 * cm, bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Title"], fontSize=18, spaceAfter=4, textColor=colors.HexColor("#0f1f33"),
    )
    section_style = ParagraphStyle(
        "Section", parent=styles["Heading2"], fontSize=13, spaceBefore=14, spaceAfter=6, textColor=colors.HexColor("#1e3a5f"),
    )
    normal_style = styles["Normal"]
    caption_style = ParagraphStyle("Caption", parent=styles["Normal"], fontSize=9, textColor=colors.gray)

    elements = []

    elements.append(Paragraph(texts["title"], title_style))
    elements.append(Paragraph(
        f"{texts['generated_at']}: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", normal_style
    ))
    elements.append(Spacer(1, 0.4 * cm))

    # --- Seção 1: Metadados ---
    elements.append(Paragraph(texts["section_metadata"], section_style))
    metadata_rows = [
        [texts["field_name"], data.image_name],
        [texts["field_path"], data.image_path],
        [texts["field_dimensions"], f"{data.width} x {data.height}"],
        [texts["field_bands"], str(data.band_count)],
        [texts["field_dtype"], data.dtype],
        [texts["field_crs"], data.crs or "—"],
        [texts["field_nodata"], str(data.nodata) if data.nodata is not None else "—"],
        [texts["field_driver"], data.driver or "—"],
        [texts["field_compression"], data.compression or "—"],
        [texts["field_composition"], f"R={data.band_composition[0]} G={data.band_composition[1]} B={data.band_composition[2]}"],
    ]
    table = Table(metadata_rows, colWidths=[5 * cm, 10 * cm])
    table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#1e3a5f")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, 0), (-1, -2), 0.4, colors.HexColor("#dddddd")),
    ]))
    elements.append(table)

    # --- Seção 2: Operações ---
    elements.append(Paragraph(texts["section_operations"], section_style))
    if data.operations:
        op_rows = [[str(i + 1), op] for i, op in enumerate(data.operations)]
        op_table = Table(op_rows, colWidths=[1.2 * cm, 13.8 * cm])
        op_table.setStyle(TableStyle([
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("LINEBELOW", (0, 0), (-1, -1), 0.3, colors.HexColor("#eeeeee")),
        ]))
        elements.append(op_table)
    else:
        elements.append(Paragraph(texts["no_operations"], normal_style))

    # --- Seção 3: Histograma ---
    histogram_png = _render_histogram_figure(data.histogram_original, data.histogram_corrected, lang)
    if histogram_png:
        elements.append(Paragraph(texts["section_histogram"], section_style))
        img_buffer = io.BytesIO(histogram_png)
        elements.append(RLImage(img_buffer, width=15 * cm, height=8.2 * cm))
        elements.append(Spacer(1, 0.2 * cm))
        elements.append(Paragraph(texts["histogram_caption"], caption_style))

    elements.append(Spacer(1, 0.8 * cm))
    elements.append(Paragraph(texts["footer"], caption_style))

    doc.build(elements)


def generate_bilingual_reports(data: ReportData, output_dir: Path, base_name: str = "relatorio") -> tuple[Path, Path]:
    """Gera os dois arquivos PDF (PT e EN) e retorna seus caminhos."""
    pt_path = output_dir / f"{base_name}_pt.pdf"
    en_path = output_dir / f"{base_name}_en.pdf"

    generate_pdf_report(data, pt_path, lang="pt")
    generate_pdf_report(data, en_path, lang="en")

    return pt_path, en_path